### ISSUE TITLE
419_methodOverriding_questions.txt 

### ISSUE THREAD

**Issue by mnguyen28** [ZacSweers/371p_practice#12]
1. What does the @Override keyword do in Java?

forces compiler to check whether you've actually overridden the method or not
http://docs.oracle.com/javase/7/docs/api/java/lang/Override.html

**Comment by ZacSweers** [comment]
Ah oops, I'll fix that. Does that change anything about the comment I wrote next to it in the code methodOverriding code?

**Comment by mnguyen28** [comment]
Yes? He commented it out because he purposely didn't override that method (has a different argument type).
